# GoReleaser configuration for RxGo library
version: 2

project_name: RxGo

# Completely disable all building for library project
builds:
  - skip: true
    goos: [linux]
    goarch: [amd64]
    main: <<<NONEXISTENT>>>

# Disable archives since this is a library
archives:
  - id: none
    builds: []

# Disable checksums
checksum:
  disable: true

# Release configuration
release:
  github:
    owner: droxer
    name: RxGo
  draft: false
  prerelease: auto
  name_template: "RxGo v{{ .Version }}"
  header: |
    ## What's New in RxGo v{{ .Version }}
    
    Modern Reactive Extensions for Go with full Reactive Streams 1.0.3 compliance.
  footer: |
    ## Installation
    
    ```bash
    go get github.com/droxer/RxGo@v{{ .Version }}
    ```

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'
      - '^style:'

# Simple hooks for library validation
before:
  hooks:
    - go mod tidy
    - go vet ./...