name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run on tags pushed to main branch
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Verify tag is on main branch
        run: |
          # Get the commit that the tag points to
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          # Check if this commit is on main branch
          if ! git branch -r --contains $TAG_COMMIT | grep -q "origin/main"; then
            echo "Error: Tag ${{ github.ref }} is not on main branch"
            exit 1
          fi
          echo "✅ Tag ${{ github.ref }} is on main branch"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}